version: '3.9'

services:
  hiclass-react:
    image: klimpavlov/hiclass-frontend-react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./firebase-serviceAccount.json:/app/firebase-serviceAccount.json
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge