version: '3'
services:
  hiclass-react:
    image: klimpavlov/hiclass-frontend-react # Укажите уже собранное изображение
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app  # если нужно подключить локальные файлы
    command: ["npm", "run", "start"]  # Запускать приложение
